### ISSUE TITLE
ByRole: can't use regex in name field

### ISSUE THREAD

**Issue by jmerkle** [lsoares/selenium-testing-library#1]
The example from the readme
`driver.findElements(ByRole("heading", name = "/as a user/i", matchTextBy = REGEX))`
doesn't work.

The `matchTextBy` param is applied to the `role` parameter and not to `name`, so the resulting call will be `(heading, { name: '/as a user/i' })` instead of `(heading, { name: /as a user/i })`

Test to reproduce this:
```
    @Test
    fun `role with regex in name parameter`() {
        driver.render(
                """<h1>something as a user something</h1>"""
        )

        val result = driver.findElements(ByRole("heading", name = "/as a user/i", matchTextBy = REGEX))

        assertEquals(expected = "something as a user something", result.single().accessibleName)
    }
```

**Comment by lsoares** [comment]
hey! I didn't notice that the `name` could also be a `TextMatch`.
Will fix it soon! thank you for pointing that out :)

**Comment by lsoares** [comment]
ok fixed. had to change the API a little bit but I think it got better. feel free to give your opinion.

**Comment by jmerkle** [comment]
thanks for fixing, it works now!

One thing i noticed however was that Intellij wasn't being smart about the import of `Regex`
when i had
```
import seleniumtestinglib.locators.ByRole

driver.findElement(ByRole(role = "heading", name = Regex("/as a user/i")))
```
it defaulted to `kotlin.text.Regex` and complained that this doesn't match `ByRole`, instead of suggesting to import `import seleniumtestinglib.coreapi.TextMatch.Regex
`
Might be a bad idea in general to use class names from stdlib. Same goes for `TextMatch.String` and possibly `TextMatch.Function`

**Comment by lsoares** [comment]
true. I was playing around and changed it a bit. what are your thoughts?

**Comment by jmerkle** [comment]
looks good to me. I can't say whether i'd prefer `JsRegex("/foo/i")` over an extension function, but that's more about personal preference.

**Comment by lsoares** [comment]
it was inspired in [toRegex
](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/to-regex.html)
I'll make the constructor public so I leave the options open.
thanks!
