### ISSUE TITLE
Deprecate `user-event` for now and drop it in next major release

### ISSUE THREAD

**Issue by elgreco247** [lsoares/selenium-testing-library#13]
As discussed here: https://github.com/lsoares/selenium-testing-library/issues/7#issuecomment-1975394608

**Comment by lsoares** [comment]
I'm still unsure what to do here. Because imagine if you're happy with testing without firefox. You'd still get value right?
unless you tell me that all `user-event` functionality exists nicely in Selenium in which case I'd say.. why not port it so it looks more TL-style? what are your thoughts?

**Comment by elgreco247** [comment]
Sorry, I seem to have misread your intentions.
Porting `user-event` functionality to Selenium should be possible (except for the clipboard part), however I think it would be very time-consuming.
I think our best shot at getting the `user-event` functionality to work in Firefox would be tweaking the async JavaScript code.

**Comment by elgreco247** [comment]
Closing the issue as it seems to be moot.

**Comment by lsoares** [comment]
You read right before... I was confused if it was worth maintaining it or not (since I'm not actively a client of this, I don't have strong opinions now). let's see what happens next then. 
4.1 is now live. thanks for all the help! I'm happy Kotlin and Java users now have a much better API!
