### ISSUE TITLE
ByRole: can't use string in `current` field

### ISSUE THREAD

**Issue by elgreco247** [lsoares/selenium-testing-library#3]
According to the testing library documentation (https://testing-library.com/docs/queries/byrole) the `current` field can be a boolean or a string, however in this library `current` is typed only as Boolean: 
https://github.com/lsoares/selenium-testing-library/blob/main/lib/src/main/kotlin/seleniumtestinglib/locators/ByRole.kt#L26

The list of all allowed strings for the `aria-current` attribute is documented here: https://www.w3.org/TR/wai-aria-1.2/#aria-current

**Comment by lsoares** [comment]
good point. How would you model the API to allow it? a new constructor with an enum?
I'm experimenting with this: 
`val result = driver.findElements(ByRole(Link).withCurrent(Page))`

otherwise there's an explosion of constructors + the compiler ambiguity calling them.

**Comment by elgreco247** [comment]
If you want to go down this path, then maybe look at how Playwright does it? They use an `...Options` class for all optional fields: E.g. `GetByRoleOptions`:
https://github.com/microsoft/playwright-java/blob/main/playwright/src/main/java/com/microsoft/playwright/Page.java#L1209

**Comment by lsoares** [comment]
That would make the general/common usage harder because you'd have more boilerplate (instantiate a builder every time rather than rely on constructor named parameters). I think it's better to make the more common operations easier.
So, I ended up doing what I suggested above. 
Thanks for the suggestion!

**Comment by lsoares** [comment]
[wait I think I could do it with the constructor instead](https://github.com/lsoares/selenium-testing-library/blob/main/lib/src/test/kotlin/seleniumtestinglib/locators/ByRoleTest.kt#L261) 👍 
so that means the other solution is not needed.

**Comment by elgreco247** [comment]
This change was not published yet, right? 
Also: shouldn't the version now be 3.7.5? (version 3.7.4 is already published)

**Comment by lsoares** [comment]
Can you check now? 3.7.5
I was experimenting with JReleaser + GitHub Actions, and it had some hiccups, but I published it manually now.
