### ISSUE TITLE
Add a `toString` method to class `JsType`

### ISSUE THREAD

**Issue by elgreco247** [lsoares/selenium-testing-library#4]
Error messages in Java Selenium tests are not very helpful because `JsType` objects have no `toString` method.
E.g.:
```
Expected condition failed: waiting for visibility of Proxy element for: 
DefaultElementLocator 'ByText(text=seleniumtestinglib.queries.JsType$JsString@5488b5c5, selector=null, exact=null, ignore=null, normalizer=null)'
```

**Comment by lsoares** [comment]
Can you give me the code that generated that so I can encode it in a test and not lose it again (I had it before)?

**Comment by lsoares** [comment]
[solved here](https://github.com/lsoares/selenium-testing-library/blob/main/lib/src/test/kotlin/seleniumtestinglib/queries/NotFoundTest.kt#L45)

Thanks for helping make the library better!
