### ISSUE TITLE
Need to add dependency to `kotlin-stdlib` in Maven Java project (since commit b0fe380 => Regex)

### ISSUE THREAD

**Issue by elgreco247** [lsoares/selenium-testing-library#6]
Since commit b0fe380 (introduction of Kotlin Regex class) I had to add a dependency to `kotlin-stdlin` in my Maven Java project pom.xml, otherwise I get the following compilation error:

```
[ERROR] .../locators/ByAltTextLocator.java:[22,21] cannot access kotlin.text.Regex
  class file for kotlin.text.Regex not found
```

If this is expected it would be nice if the additional dependency was mentioned in the docs.

**Comment by lsoares** [comment]
you're right. I wasn't thinking of Java users.
I replaced Regex with Pattern. Can you check?
Also, I'm curious: if I had both overloads, would it work without the dependency if you didn't call the Regex ones?

**Comment by elgreco247** [comment]
It doesn't matter whether you call the Regex overload or not; it just doesn't compile.

**Comment by lsoares** [comment]
it's weird but I always used Regex internally - it was always working for you before with that - without the dep.

now I removed it from the public API only. can you double-check it? if it compiles?

the other question was: if I push one that has Regex as part of the public API but you would not make use of it, would it still force you to have the dep?

**Comment by elgreco247** [comment]
I think the issue occurs when the kotlin Regex is part of the public API, whether you make use of it or not.

**Comment by lsoares** [comment]
Ok then it should be good now right?

**Comment by lsoares** [comment]
new version released: 3.7.8
feel free to test it. No hurries. BTW, thanks for the feedback for improvements!

**Comment by elgreco247** [comment]
Version 3.7.8 solved the issue. thx!

**Comment by lsoares** [comment]
[This has been here for a long time.. ](https://github.com/lsoares/selenium-testing-library/commit/9e31c9f4c688547c0d148594245bfcbc3a6e507b#diff-cbb885eaeb994cf68f1af085ba1557822c90c991e196a0dd26ef192346054b6cL86) so I wonder how it's not a problem for you now as it's part of the public API.
