### ISSUE TITLE
Using regular expresions or functions for `TextMatch` is not working in Firefox

### ISSUE THREAD

**Issue by elgreco247** [lsoares/selenium-testing-library#7]
Due to an issue with the Firefox geckodriver (https://github.com/mozilla/geckodriver/issues/1798) the following dom-testing-library JS-code is not working in Firefox:

```javascript
        if (matcher instanceof Function) {
            return matcher(normalizedText, node);
        } else if (matcher instanceof RegExp) {
            const result = matchRegExp(matcher, normalizedText);
            console.log("result", result);
            return result;
        } else {
            return normalizedText === String(matcher);
        }
 ```

The reason is that each Selenium JavaScript execution in Firefox has its own `RegExp` and `Function` definition; this Java example returns false when using the FirefoxDriver:

```java
        ((JavascriptExecutor)driver).executeScript("""
                 window.isFunction = function(probe) {
                     return (probe instanceof Function);
                 };
                """);

        var isFunction = ((JavascriptExecutor) driver).executeScript("""
                return isFunction(Function('a', 'b', 'return a + b'));
                """);
       // isFunction is false
```

One possible workaround would be saving the `Function` definition from the first execution as a `window` property and using it in the second:

```java
        ((JavascriptExecutor)driver).executeScript("""
                 window.__TL__Function = Function;
                 window.isFunction = function(probe) {
                     return (probe instanceof Function);
                 };
                """);

        var isFunction = ((JavascriptExecutor) driver).executeScript("""
                return isFunction(__TL__Function('a', 'b', 'return a + b'));
                """);
       // isFunction is true
```

For this workaround to work in the seleniumtestinglib the following changes would be needed:
- Add `window.__TL__Function = Function;` and `window.__TL__RegExp = RegExp;` to this file: https://github.com/lsoares/selenium-testing-library/blob/main/testing-library/src/testing-library.js
- Wrap each `JsFunction` in  a `__TL__Function`: `__TL__Function("content", "element", "return (" + origFunc + ").apply(this, arguments)")`
- Use `__TL__RegExp` instead of `/pattern/` here: https://github.com/lsoares/selenium-testing-library/blob/main/lib/src/main/kotlin/seleniumtestinglib/queries/Api.kt#L67

**Comment by elgreco247** [comment]
Would it be possible to implement the aforementioned first change (adding `window.__TL__Function = Function` and `window.__TL__RegExp = RegExp` to https://github.com/lsoares/selenium-testing-library/blob/main/testing-library/src/testing-library.js) as a first step?
Then those `window` properties can be used in user-land to get regex and function locators working in Firefox.

**Comment by lsoares** [comment]
ok that's an easy step then. I can do that easily. 
also feel free do open an MR if you can do it before me.

**Comment by lsoares** [comment]
Ok, I did that first step. I tried doing the remaining, but the code gets a bit messy (and maybe buggy) because of all the escaping that needs to be done. maybe I release it this way just as a first try.

**Comment by lsoares** [comment]
Released in `4.0.0`.

BTW, I modified the API to become closer to the Selenium patterns.
you'll need to change the invocations. e.g. `ByRole` to `TL.By.role` (It becomes similar to `By.cssSelector`). what do you think?

**Comment by elgreco247** [comment]
Thx for the release. And the new API is nice too. 
What do you think about adding the `@JvmOverloads` annotation to the new API? It would make it easier to use for Java programmers.

**Comment by lsoares** [comment]
Thanks for the feedback. I added that (and JvmStatic) and tested it in Java, and it looks better (except for ByRole), but in general, without named parameters in Java, it's still painful to pass nulls till your desired argument. If you know how to make it better for Java users...

**Comment by lsoares** [comment]
[This is the smallest I can get to in Java.](https://github.com/lsoares/selenium-testing-library/blob/main/lib/src/test/java/JavaTest.java#L29). What are your thoughts?

**Comment by elgreco247** [comment]
Wow! That's really nice! 
I have just one suggestion: `roleOptions` should only include all optional parameters (not `Role` which is mandatory). So I would remove the constructor parameter of the class `RoleOptions` and change the signature of the new function from `role(options: RoleOptions)` to `role(role: Role, options: RoleOptions)`.
What do you think?
BTW, if we have roleOptions then we don't need the `@JvmOverloads` annotation for roles anymore, IMHO.

**Comment by lsoares** [comment]
After your suggestion, I got carried away and decoupled the Java API from the Kotlin API because if so, the Java one can get even simpler. [Is it better](https://github.com/lsoares/selenium-testing-library/blob/main/lib/src/test/java/JavaTest.java#L28)?

**Comment by elgreco247** [comment]
Like it!

**Comment by elgreco247** [comment]
BTW, I think I have a solution for the original problem of this issue; what if we rewrote `testing-library.js` as follows:

```javascript
import { screen, fireEvent } from '@testing-library/dom'

window.__TL__ = {
    screen,
    fireEvent
}


if (/Firefox/.test(navigator.userAgent)) {
    window.__TL__.screen = {
        ...window.__TL__.screen,
        queryAllByRole            : (role,  options) => screen.queryAllByRole            (role, wrapRoleOptions(options)),
        queryAllByLabelText       : (text,  options) => screen.queryAllByLabelText       (wrapTextMatch(text), wrapTextOptions(options)),
        queryAllByPlaceholderText : (text,  options) => screen.queryAllByPlaceholderText (wrapTextMatch(text), wrapTextOptions(options)),
        queryAllByText            : (text,  options) => screen.queryAllByText            (wrapTextMatch(text), wrapTextOptions(options)),
        queryAllByDisplayValue    : (value, options) => screen.queryAllByDisplayValue    (wrapTextMatch(value), wrapTextOptions(options)),
        queryAllByAltText         : (text,  options) => screen.queryAllByAltText         (wrapTextMatch(text), wrapTextOptions(options)),
        queryAllByTitle           : (title, options) => screen.queryAllByTitle           (wrapTextMatch(title), wrapTextOptions(options)),
        queryAllByTestId          : (text,  options) => screen.queryAllByTestId          (wrapTextMatch(text), wrapTextOptions(options)),
    }
    function wrapRoleOptions(options) {
        return options && { ...options,
            name: wrapTextMatch(options.name),
            description: wrapTextMatch(options.description),
            value: options.value && { ...options.value, text: wrapTextMatch(options.value.text) }
        }
    }
    function wrapTextOptions(options) {
        return options && { ...options, normalizer: wrapFunction(options.normalizer) }
    }
    function wrapTextMatch(maybeRegexOrFunc) {
        if (Object.prototype.toString.call(maybeRegexOrFunc) === "[object RegExp]") {
            return new RegExp(maybeRegexOrFunc.source, maybeRegexOrFunc.flags)
        }
        return wrapFunction(maybeRegexOrFunc)
    }
    function wrapFunction(maybeFunc) {
        if (Object.prototype.toString.call(maybeFunc) === "[object Function]") {
            return (content, element) => maybeFunc.call(null, content, element)
        }
        return maybeFunc
    }
}
```

Notice that I moved `window.screen` (and `window.fireEvent`) to the object `window.__TL__` to avoid clashes with the existing `window.screen` property: https://developer.mozilla.org/en-US/docs/Web/API/Window/screen.
This of course means that the kotlin method `JavascriptExecutor.findElements` would have to be adjusted accordingly.

**Comment by lsoares** [comment]
everything abstracted here.. that's clever! what would it be missing? isn't that abstraction everything? just using the new variable holding screen right?
do you want to do a PR? at this point you know more than me about this topic.
I think it's worth having a few tests with a firefox driver.

**Comment by elgreco247** [comment]
I have opened a new issue for the clash with the existing `window.screen` property: https://github.com/lsoares/selenium-testing-library/issues/9

**Comment by lsoares** [comment]
All the tests pass in Firefox except under `interactions` tests. I get:
`org.openqa.selenium.JavascriptException: SyntaxError: await is only valid in async functions, async generators and modules`

At this point I'm not sure if it's worth fixing them or deleting the functionality ([user-event](https://testing-library.com/docs/user-event/intro)) since it's offered through Selenium (or it could be ported). Let me know what your thoughts are.

**Comment by elgreco247** [comment]
I don't use the `user-event` functionality, but if you want to fix it you could just use `executeAsyncScript` instead of `executeScript`.
E.g. instead of 
```
driver.executeScript("await user.copy()")
```
use
```
driver.executeAsyncScript("user.copy().then(() => arguments[arguments.length - 1]()");
```

**Comment by elgreco247** [comment]
> `driver.executeAsyncScript("user.copy().then(() => arguments[arguments.length - 1]()");`

This solution leads to some failures with the Chrome driver.

I tried it with `driver.executeAsyncScript("(async () => {await user.copy(); arguments[arguments.length-1]()})()")` and now there are no failures with Chrome but still 5 `interactions` failures with Firefox (down from 37).

BTW, there are also 7 `jestdom` failures with Firefox (unrelated to the `user-event` fix discussed above).

**Comment by lsoares** [comment]
accepted your suggestion of just running a subset of tests in Firefox.
