### ISSUE TITLE
TL locators can not be used relative to a WebElement (e.g. when chaining locators)

### ISSUE THREAD

**Issue by elgreco247** [lsoares/selenium-testing-library#8]
The following test should be passing:

```java
    @Test
    public void chainingTest() {
        var driver = new ChromeDriver();
        try {
            driver.get("https://www.selenium.dev/selenium/web/nestedElements.html");
            var checkboxes = driver.findElements(new ByChained(By.tagName("form"), By.tagName("input"))); // 8 results
            var checkboxesTL = driver.findElements(new ByChained(TL.By.role(Role.Form), TL.By.role(Role.CheckBox))); // 64 results; should be 8
            assertEquals(checkboxes.size(), checkboxesTL.size()); 
        } finally {
            driver.quit();
        }
    }
```

The problem seems to be that in the method `TL.findElements` there is no distinction between a `SearchContext` that is a `WebDriver` and a `SearchContext` that is a `WebElement` (like it's done here: https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/By.java#L137).
If the `SearchContext` is a `WebElement` then calling `screen.queryAllBy*(...)` functions in `JavascriptExecutor.findElements` is wrong (because the container for those queries is always `document.body`); instead the `queryAllBy*(container, ...)` functions should be called with the `SearchContext` object as their first argument (`container`).

**Comment by lsoares** [comment]
I gave it a first try, but some tests are failing.. not sure why yet.
I isolated the issue in a test (`ContextText`).
BTW, if you want to join as a maintainer, please say so. It would simplify the process, and it would be great to count on your know-how.

**Comment by elgreco247** [comment]
This should fix the failing tests:
```
diff --git a/lib/src/main/kotlin/seleniumtestinglib/Core.kt b/lib/src/main/kotlin/seleniumtestinglib/Core.kt
--- a/lib/src/main/kotlin/seleniumtestinglib/Core.kt	(revision 6f3d13e8024847574f206ad7120ea01da5c14044)
+++ b/lib/src/main/kotlin/seleniumtestinglib/Core.kt	(date 1709549781635)
@@ -2,6 +2,7 @@
 
 import org.openqa.selenium.JavascriptExecutor
 import org.openqa.selenium.SearchContext
+import org.openqa.selenium.WebDriver
 import org.openqa.selenium.WebElement
 import seleniumtestinglib.TextMatch.JsExpression
 import seleniumtestinglib.TextMatch.JsString
@@ -288,9 +289,12 @@
     @Suppress("unchecked_cast")
     override fun findElements(context: SearchContext): List<WebElement> {
         val jsExecutor = (getWebDriver(context) as JavascriptExecutor)
-        jsExecutor.ensureScript("testing-library.js", "window.__TL__?.screen?.queryAllByTestId")
+        jsExecutor.ensureScript("testing-library.js", "window.__TL__?.queryAllByTestId")
         return jsExecutor.executeScript(buildString {
-            append("return window.__TL__.screen.queryAllBy$by(")
+            append("return window.__TL__.queryAllBy$by(")
+            (context as? WebDriver)?.let {
+                append("document.body, ")
+            }
             (context as? WebElement)?.let {
                 append("arguments[0], ")
             }
```
Not sure if this is the optimal way to code it in Kotlin...

**Comment by lsoares** [comment]
awesome! it works! you're on 🔥
but why is it needed? isn't the body the default?

**Comment by elgreco247** [comment]
The `queryAllBy*` functions need the container element as their first parameter. The `screen.queryAllBy*` functions are an alias for the `queryAllBy*` functions with `document.body` as the container element.

**Comment by lsoares** [comment]
awesome. can we close? I can publish the library afterward

**Comment by elgreco247** [comment]
Maybe merge https://github.com/lsoares/selenium-testing-library/pull/12 before releasing?
