### ISSUE TITLE
The JavaScript code of this library clashes with the window.screen property

### ISSUE THREAD

**Issue by elgreco247** [lsoares/selenium-testing-library#9]
In the file https://github.com/lsoares/selenium-testing-library/blob/main/testing-library/src/testing-library.js the `window.screen` property (https://developer.mozilla.org/en-US/docs/Web/API/Window/screen) is overwritten.
It would be better if this library would use an own, uncommon `window` property (e.g. `window.__TL__`).
See also https://github.com/lsoares/selenium-testing-library/issues/7#issuecomment-1974794381

**Comment by lsoares** [comment]
good catch. Since your suggestion in the other issue solves both things, let's do it there.
